// packages/react/src/ui/TimeAxis.tsx
import { useLayoutEffect, useRef } from 'react';

import { formatTime, resolveAxisFontSize, resolveAxisTextColor } from '@wick-charts/core';

import { useChartInstance } from '../context';
import { useVisibleRange } from '../store-bridge';
import { AXIS_LABEL_CLEANUP_MS, AXIS_LABEL_FADE_CSS } from './axisFade';

interface TrackedTick {
  opacity: number;
  addedAt: number;
  fadedAt?: number;
}

export interface TimeAxisProps {
  /** Desired number of labels (≥ 2). Overrides chart-level `axis.x.labelCount`. */
  labelCount?: number;
  /** Minimum pixel gap between adjacent labels (hard floor). Overrides chart-level. */
  minLabelSpacing?: number;
}

export function TimeAxis({ labelCount, minLabelSpacing }: TimeAxisProps = {}) {
  const chart = useChartInstance();
  useVisibleRange(chart); // subscribe to viewport changes so ticks re-render

  useLayoutEffect(() => {
    chart.setTimeAxisLabelDensity({
      labelCount: labelCount ?? null,
      minLabelSpacing: minLabelSpacing ?? null,
    });

    return () => {
      chart.setTimeAxisLabelDensity({ labelCount: null, minLabelSpacing: null });
    };
  }, [chart, labelCount, minLabelSpacing]);
  const theme = chart.getTheme();
  const dataInterval = chart.getDataInterval();
  const { ticks: currentTicks, tickInterval } = chart.timeScale.niceTickValues(dataInterval);
  const currentSet = new Set(currentTicks);

  // Persistent map: tick value → tracked state
  const mapRef = useRef<Map<number, TrackedTick>>(new Map());
  const map = mapRef.current;
  const now = performance.now();

  // Mark current ticks as visible
  for (const t of currentTicks) {
    if (!map.has(t)) {
      map.set(t, { opacity: 1, addedAt: now });
    } else {
      map.get(t)!.opacity = 1;
    }
  }

  // Mark missing ticks for fade-out
  for (const [t, entry] of map) {
    if (!currentSet.has(t)) {
      if (entry.opacity !== 0) {
        entry.opacity = 0;
        entry.fadedAt = now;
      }
    }
  }

  // Clean up ticks that have finished fading. Buffer = AXIS_LABEL_FADE_MS + 250
  // (one transition + a frame margin) so the DOM node sticks around past the
  // visible fade.
  for (const [t, entry] of map) {
    if (entry.opacity === 0 && entry.fadedAt !== undefined && now - entry.fadedAt > AXIS_LABEL_CLEANUP_MS) {
      map.delete(t);
    }
  }

  // Collect all ticks to render (current + fading out)
  const allTicks = Array.from(map.entries());

  return (
    <div
      style={{
        position: 'absolute',
        left: 0,
        bottom: 0,
        right: chart.yAxisWidth,
        height: chart.xAxisHeight,
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
      }}
    >
      {allTicks.map(([time, entry]) => {
        const x = chart.timeScale.timeToX(time);
        return (
          <span
            key={time}
            style={{
              position: 'absolute',
              left: x,
              transform: 'translateX(-50%)',
              color: resolveAxisTextColor(theme, 'x'),
              fontSize: resolveAxisFontSize(theme, 'x'),
              fontFamily: theme.typography.fontFamily,
              userSelect: 'none',
              whiteSpace: 'nowrap',
              opacity: entry.opacity,
              transition: AXIS_LABEL_FADE_CSS,
              willChange: 'opacity',
            }}
          >
            {formatTime(time, tickInterval)}
          </span>
        );
      })}
    </div>
  );
}

// packages/vue/src/ui/TimeAxis.vue
<script setup lang="ts">
import { formatTime, resolveAxisFontSize, resolveAxisTextColor } from '@wick-charts/core';
import { computed, onUnmounted, watch } from 'vue';

import { useVisibleRange } from '../composables';
import { useChartInstance } from '../context';

const props = defineProps<{
  /** Desired number of labels (≥ 2). Overrides chart-level `axis.x.labelCount`. */
  labelCount?: number;
  /** Minimum pixel gap between adjacent labels (hard floor). Overrides chart-level. */
  minLabelSpacing?: number;
}>();

interface TrackedTick {
  opacity: number;
  addedAt: number;
}

const chart = useChartInstance();
const visibleRange = useVisibleRange(chart);

const applyDensity = () => {
  chart.setTimeAxisLabelDensity({
    labelCount: props.labelCount ?? null,
    minLabelSpacing: props.minLabelSpacing ?? null,
  });
};
applyDensity();
watch(() => [props.labelCount, props.minLabelSpacing], applyDensity);
onUnmounted(() => {
  chart.setTimeAxisLabelDensity({ labelCount: null, minLabelSpacing: null });
});

const tickMap = new Map<number, TrackedTick>();

const theme = computed(() => chart.getTheme());

const tickData = computed(() => {
  // Access visibleRange.value to track dependency
  void visibleRange.value;

  const dataInterval = chart.getDataInterval();
  const { ticks: currentTicks, tickInterval } = chart.timeScale.niceTickValues(dataInterval);
  const currentSet = new Set(currentTicks);
  const now = performance.now();

  // Mark current ticks as visible
  for (const t of currentTicks) {
    if (!tickMap.has(t)) {
      tickMap.set(t, { opacity: 1, addedAt: now });
    } else {
      tickMap.get(t)!.opacity = 1;
    }
  }

  // Mark missing ticks for fade-out
  for (const [t, entry] of tickMap) {
    if (!currentSet.has(t)) {
      entry.opacity = 0;
    }
  }

  // Clean up old faded-out ticks
  for (const [t, entry] of tickMap) {
    if (entry.opacity === 0 && now - entry.addedAt > 5000) {
      tickMap.delete(t);
    }
  }

  return {
    allTicks: Array.from(tickMap.entries()),
    tickInterval,
  };
});
</script>

<template>
  <div
    :style="{
      position: 'absolute',
      left: '0',
      bottom: '0',
      right: chart.yAxisWidth + 'px',
      height: chart.xAxisHeight + 'px',
      pointerEvents: 'none',
      display: 'flex',
      alignItems: 'center',
    }"
  >
    <span
      v-for="[time, entry] in tickData.allTicks"
      :key="time"
      :style="{
        position: 'absolute',
        left: chart.timeScale.timeToX(time) + 'px',
        transform: 'translateX(-50%)',
        color: resolveAxisTextColor(theme, 'x'),
        fontSize: resolveAxisFontSize(theme, 'x') + 'px',
        fontFamily: theme.typography.fontFamily,
        userSelect: 'none',
        whiteSpace: 'nowrap',
        opacity: entry.opacity,
        transition: 'opacity 0.25s ease',
        willChange: 'opacity',
      }"
    >
      {{ formatTime(time, tickData.tickInterval) }}
    </span>
  </div>
</template>
