// packages/svelte/src/ui/YAxis.svelte
<script lang="ts">
import { type ChartInstance, resolveAxisFontSize, resolveAxisTextColor, type ValueFormatter } from '@wick-charts/core';
import { onDestroy } from 'svelte';

import { getChartContext } from '../context';
import { createYRange } from '../stores';

/** Custom tick-label formatter. Overrides the built-in range-adaptive default. */
export let format: ValueFormatter | undefined = undefined;
/**
 * Desired number of labels (≥ 2). Overrides any chart-level `axis.y.labelCount`.
 * Realized count may differ ±1 after the 1-2-5 snap.
 */
export let labelCount: number | undefined = undefined;
/** Minimum pixel gap between adjacent labels (hard floor). Overrides chart-level. */
export let minLabelSpacing: number | undefined = undefined;

interface TrackedTick {
  opacity: number;
  addedAt: number;
}

const chartStore = getChartContext();
const tickMap = new Map<number, TrackedTick>();

let yRangeUnsub: (() => void) | null = null;
let allTicks: [number, TrackedTick][] = [];

$: {
  const chart = $chartStore;
  if (chart && !yRangeUnsub) {
    const yRangeStore = createYRange(chart);
    yRangeUnsub = yRangeStore.subscribe(() => {
      updateTicks(chart);
    });
  }
}

function updateTicks(chart: ChartInstance) {
  const currentTicks = chart.yScale.niceTickValues();
  const currentSet = new Set(currentTicks);
  const now = performance.now();

  for (const p of currentTicks) {
    if (!tickMap.has(p)) {
      tickMap.set(p, { opacity: 1, addedAt: now });
    } else {
      tickMap.get(p)!.opacity = 1;
    }
  }

  for (const [p, entry] of tickMap) {
    if (!currentSet.has(p)) {
      entry.opacity = 0;
    }
  }

  for (const [p, entry] of tickMap) {
    if (entry.opacity === 0 && now - entry.addedAt > 5000) {
      tickMap.delete(p);
    }
  }

  allTicks = Array.from(tickMap.entries());
}

onDestroy(() => {
  yRangeUnsub?.();
});

$: chart = $chartStore;
$: theme = chart?.getTheme();

// Route the formatter through yScale so Crosshair / YLabel fallback use
// the same function as the axis labels.
$: if (chart) {
  chart.yScale.setFormat(format ?? null);
}
onDestroy(() => {
  $chartStore?.yScale.setFormat(null);
});

// Hold a stable reference to the chart so onDestroy still has it when the
// parent ChartContainer's onDestroy has already cleared the store.
let densityChart: typeof chart = null;
$: if (chart) {
  densityChart = chart;
  chart.setYAxisLabelDensity({
    labelCount: labelCount ?? null,
    minLabelSpacing: minLabelSpacing ?? null,
  });
}
onDestroy(() => {
  densityChart?.setYAxisLabelDensity({ labelCount: null, minLabelSpacing: null });
});
</script>

{#if chart && theme}
  <div
    style="position:absolute;right:0;top:0;bottom:{chart.xAxisHeight}px;width:{chart.yAxisWidth}px;pointer-events:none;"
  >
    {#each allTicks as [price, entry] (price)}
      <span
        style="position:absolute;right:8px;top:{chart.yScale.valueToY(price)}px;transform:translateY(-50%);color:{resolveAxisTextColor(theme, 'y')};font-size:{resolveAxisFontSize(theme, 'y')}px;font-family:{theme.typography.fontFamily};font-variant-numeric:tabular-nums;user-select:none;opacity:{entry.opacity};transition:opacity 0.25s ease;will-change:opacity;"
      >
        {chart.yScale.formatY(price)}
      </span>
    {/each}
  </div>
{/if}

// packages/react/src/ui/YAxis.tsx
import { useLayoutEffect, useRef } from 'react';

import { resolveAxisFontSize, resolveAxisTextColor, type ValueFormatter } from '@wick-charts/core';

import { useChartInstance } from '../context';
import { useYRange } from '../store-bridge';
import { AXIS_LABEL_CLEANUP_MS, AXIS_LABEL_FADE_CSS } from './axisFade';

interface TrackedTick {
  opacity: number;
  addedAt: number;
  fadedAt?: number;
}

export interface YAxisProps {
  /**
   * Custom tick-label formatter. When supplied, overrides the built-in
   * range-adaptive formatter for this axis.
   */
  format?: ValueFormatter;
  /**
   * Desired number of labels (≥ 2). Overrides any chart-level `axis.y.labelCount`.
   * Realized count may differ ±1 after the 1-2-5 snap.
   */
  labelCount?: number;
  /** Minimum pixel gap between adjacent labels (hard floor). Overrides chart-level. */
  minLabelSpacing?: number;
}

export function YAxis({ format, labelCount, minLabelSpacing }: YAxisProps = {}) {
  const chart = useChartInstance();
  useYRange(chart); // subscribe to viewport changes so ticks re-render

  // Route the prop through yScale so the *same* formatter drives every
  // surface that reads `yScale.formatY()` (Crosshair, YLabel fallback).
  useLayoutEffect(() => {
    chart.yScale.setFormat(format ?? null);

    return () => chart.yScale.setFormat(null);
  }, [chart, format]);

  useLayoutEffect(() => {
    chart.setYAxisLabelDensity({
      labelCount: labelCount ?? null,
      minLabelSpacing: minLabelSpacing ?? null,
    });

    return () => {
      chart.setYAxisLabelDensity({ labelCount: null, minLabelSpacing: null });
    };
  }, [chart, labelCount, minLabelSpacing]);

  const theme = chart.getTheme();
  const currentTicks = chart.yScale.niceTickValues();
  const currentSet = new Set(currentTicks);

  const mapRef = useRef<Map<number, TrackedTick>>(new Map());
  const map = mapRef.current;
  const now = performance.now();

  for (const p of currentTicks) {
    if (!map.has(p)) {
      map.set(p, { opacity: 1, addedAt: now });
    } else {
      map.get(p)!.opacity = 1;
    }
  }

  for (const [p, entry] of map) {
    if (!currentSet.has(p)) {
      if (entry.opacity !== 0) {
        entry.opacity = 0;
        entry.fadedAt = now;
      }
    }
  }

  // Cleanup buffer matches the shared AXIS_LABEL_CLEANUP_MS — see axisFade.ts.
  for (const [p, entry] of map) {
    if (entry.opacity === 0 && entry.fadedAt !== undefined && now - entry.fadedAt > AXIS_LABEL_CLEANUP_MS) {
      map.delete(p);
    }
  }

  const allTicks = Array.from(map.entries());

  return (
    <div
      style={{
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: chart.xAxisHeight,
        width: chart.yAxisWidth,
        pointerEvents: 'none',
      }}
    >
      {allTicks.map(([price, entry]) => {
        const y = chart.yScale.valueToY(price);
        return (
          <span
            key={price}
            style={{
              position: 'absolute',
              right: 8,
              top: y,
              transform: 'translateY(-50%)',
              color: resolveAxisTextColor(theme, 'y'),
              fontSize: resolveAxisFontSize(theme, 'y'),
              fontFamily: theme.typography.fontFamily,
              fontVariantNumeric: 'tabular-nums',
              userSelect: 'none',
              opacity: entry.opacity,
              transition: AXIS_LABEL_FADE_CSS,
              willChange: 'opacity',
            }}
          >
            {chart.yScale.formatY(price)}
          </span>
        );
      })}
    </div>
  );
}
